In [1]:
#looks like conway's game of life

In [78]:
f= open('input-24.txt','r')
dat = f.readlines()
f.close()

In [7]:
dat

['.#..#\n', '#..##\n', '##..#\n', '##.##\n', '#..##\n']

In [91]:
testdat = ['....#\n',
'#..#.\n',
'#..##\n',
'..#..\n',
'#....\n',]

In [79]:
grid = np.zeros((7,7))

for y,char in enumerate(dat):
    for x,c in enumerate(char[0:-1]):
        #print(c)
        if c == '#':
            grid[y+1,x+1] = 1
        
print(grid[1:6,1:6])


[[0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1.]
 [1. 1. 0. 1. 1.]
 [1. 0. 0. 1. 1.]]


In [80]:
x=4
y=1
grid[x,y]
bugtally = np.sum(grid[y-1:y+2,x-1:x+2]==1)
bugtally

3

In [81]:

grid[y-1:y+2,x-1:x+2]

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 1.]])

In [141]:
import copy 

#Each minute, The bugs live and die based on the number of bugs in the four adjacent tiles:

#A bug dies (becoming an empty space) unless there is exactly one bug adjacent to it.

#An empty space becomes infested with a bug if exactly one or two bugs are adjacent to it.

import numpy as np
grid = np.zeros((7,7)).astype(int)

for y,char in enumerate(dat):
    for x,c in enumerate(char[0:-1]):
        #print(c)
        if c == '#':
            grid[y+1,x+1] = 1
        elif c == '.':
            grid[y+1,x+1] = 0


        
print(grid[1:6,1:6])


seen = set()
gen = 0
while True:
    nextgrid = np.zeros((7,7)).astype(int)
    bcount = np.zeros((7,7)).astype(int)
    for x in range(1,6):
        for y in range(1,6):
            bugtally = 0
            bugtally = grid[y-1,x]+grid[y+1,x]+grid[y,x+1]+grid[y,x-1]
            bcount[y,x]=bugtally

            #bugs die if next to another bug
            
            if grid[y,x] == 0 and (bugtally == 1):
                nextgrid[y,x]=1
            
            if grid[y,x] == 0 and (bugtally == 2):
                nextgrid[y,x]=1
                
            if grid[y,x] == 1 and bugtally == 1:
                nextgrid[y,x]=1


    if False:
        print(' -- ')
        print(bcount[1:6,1:6])
        print(' ')
        print(nextgrid[1:6,1:6])
        print(' -- ')


    grid = copy.deepcopy(nextgrid)
    sighted = ''.join(list(map(str,list(map(int,list(np.ravel(nextgrid[1:6,1:6])))))))
    if sighted in seen:
        print('finished at gen:',gen)
        repeated = sighted
        break
    else:
        seen.add(sighted)
        gen+=1

[[0 1 0 0 1]
 [1 0 0 1 1]
 [1 1 0 0 1]
 [1 1 0 1 1]
 [1 0 0 1 1]]
finished at gen: 74


In [142]:
#..#.
####.
###.#
##.##
.##..

SyntaxError: invalid syntax (<ipython-input-142-c92f6fac5556>, line 5)

In [143]:
seen

{'0000000000000010000100111',
 '0000000001000110011001100',
 '0000100000001110011010100',
 '0000100011001000100111010',
 '0001000010110101111011100',
 '0001000011001101110101010',
 '0001000111010011100101110',
 '0001100110010111111010101',
 '0010000010100110110100111',
 '0010000111110010100001100',
 '0010100000100110011010100',
 '0010100000101000000110011',
 '0010101100110010000010100',
 '0010101100111000000010000',
 '0011000010100111110000100',
 '0011100000100001000110010',
 '0011100101110001000011001',
 '0011100111001110010111111',
 '0011100111110011100111110',
 '0011101100111101011110011',
 '0011111101000010000100010',
 '0100001000010001100010000',
 '0100011000001100011100011',
 '0100011101011010000101110',
 '0100110001000010000011100',
 '0101010011001011101101110',
 '0101010101010111011101110',
 '0101010111011001100001000',
 '0101010111011011100101110',
 '0101110010001001100010000',
 '0101110011000011100111110',
 '0101110110010111111110110',
 '0110000110000011100001001',
 '01100101

In [144]:
repeated

'0000100011001000100111010'

In [147]:
total = 0
for i,c in enumerate(repeated):
    print(i,c,pow(2,i))
    if c =='1':
        total+=pow(2,i)
        
        
print(total)

0 0 1
1 0 2
2 0 4
3 0 8
4 1 16
5 0 32
6 0 64
7 0 128
8 1 256
9 1 512
10 0 1024
11 0 2048
12 1 4096
13 0 8192
14 0 16384
15 0 32768
16 1 65536
17 0 131072
18 0 262144
19 1 524288
20 1 1048576
21 1 2097152
22 0 4194304
23 1 8388608
24 0 16777216
12129040


In [146]:
8635242

8635242

In [148]:
# each map is a recursive grid. what's the number of bugs after 200 mins. 
#Initially, no other levels contain bugs.
# expand the grid to (501 dims,7,7) 


# need a function that fetches the neighbors: 

levelzero = 250

grid = np.zeros((500,7,7)).astype(int)

for y,char in enumerate(dat):
    for x,c in enumerate(char[0:-1]):
        #print(c)
        if c == '#':
            grid[levelzero,y+1,x+1] = 1
        elif c == '.':
            grid[levelzero,y+1,x+1] = 0

In [ ]:
     |     |         |     |     
  1  |  2  |    3    |  4  |  5  
     |     |         |     |     
-----+-----+---------+-----+-----
     |     |         |     |     
  6  |  7  |    8    |  9  |  10 
     |     |         |     |     
-----+-----+---------+-----+-----
     |     |A|B|C|D|E|     |     
     |     |-+-+-+-+-|     |     
     |     |F|G|H|I|J|     |     
     |     |-+-+-+-+-|     |     
 11  | 12  |K|L|?|N|O|  14 |  15 
     |     |-+-+-+-+-|     |     
     |     |P|Q|R|S|T|     |     
     |     |-+-+-+-+-|     |     
     |     |U|V|W|X|Y|     |     
-----+-----+---------+-----+-----
     |     |         |     |     
 16  | 17  |    18   |  19 |  20 
     |     |         |     |     
-----+-----+---------+-----+-----
     |     |         |     |     
 21  | 22  |    23   |  24 |  25 
     |     |         |     |     

In [219]:
def get_adjacent_tally(grid,level,x,y):
    
    if x==3 and y==2:
        #number 8
        tally = np.sum(grid[level-1,1,:])+grid[level,y-1,x]+grid[level,y,x+1]+grid[level,y,x-1]
    elif x==2 and y==3:
        # number 12
        tally = np.sum(grid[level-1,:,1])+grid[level,y-1,x]+grid[level,y+1,x]+grid[level,y,x-1]
    elif x==4 and y==3:
        # number 14
        tally = np.sum(grid[level-1,:,6])+grid[level,y-1,x]+grid[level,y+1,x]+grid[level,y,x+1]
    elif x==4 and y==3:
        # number 18
        tally = np.sum(grid[level-1,6,:])+grid[level,y+1,x]+grid[level,y,x+1]+grid[level,y,x-1]
        
    
    elif y==1:
        if x>1 and x<6:
            # row 1, x: 2 to 4
            # all their tops are tile 8.
            tally = grid[level+1,2,3] + grid[level,y,x+1]+grid[level,y,x-1]+grid[level,y+1,x]
        if x==1:
            tally = grid[level+1,2,3] + grid[level+1,3,2]+grid[level,y+1,x]+grid[level,y,x+1]
        if x==5:
            tally = grid[level+1,2,3] + grid[level+1,3,4]+grid[level,y+1,x]+grid[level,y,x-1]

    elif y==5:
        if x>1 and x<6:
            # row 1, x: 2 to 4
            # all their bottoms are tile 18.
            tally = grid[level+1,4,3] + grid[level,y,x+1]+grid[level,y,x-1]+grid[level,y-1,x]
        if x==1:
            tally = grid[level+1,4,3] + grid[level+1,3,2]+grid[level,y-1,x]+grid[level,y,x+1]
        if x==5:
            tally = grid[level+1,4,3] + grid[level+1,3,4]+grid[level,y-1,x]+grid[level,y,x-1]

    elif x==1 and (y==2 or y==3 or y==4):
        tally = grid[level+1,3,1] + grid[level,y,x+1]+ grid[level,y+1,x]+ grid[level,y-1,x]

    elif x==5 and (y==2 or y==3 or y==4):
        tally = grid[level+1,3,4] + grid[level,y,x-1]+ grid[level,y+1,x]+ grid[level,y-1,x]
    elif x ==3 and y ==4:
        tally = np.sum(grid[level-1,5,:]) + grid[level,y,x-1]+ grid[level,y+1,x]+ grid[level,y,x+1]
    elif x ==2 and y ==2:
        tally = grid[level,y,x+1]+grid[level,y,x-1]+ grid[level,y+1,x]+ grid[level,y-1,x]
    elif x ==2 and y ==4:
        tally = grid[level,y,x+1]+grid[level,y,x-1]+ grid[level,y+1,x]+ grid[level,y-1,x]

    elif x ==4 and y ==2:
        tally = grid[level,y,x+1]+grid[level,y,x-1]+ grid[level,y+1,x]+ grid[level,y-1,x]

    elif x ==4 and y ==4:
        tally = grid[level,y,x+1]+grid[level,y,x-1]+ grid[level,y+1,x]+ grid[level,y-1,x]

    elif x ==3 and y ==3:
        tally = grid[level,y,x+1]+grid[level,y,x-1]+ grid[level,y+1,x]+ grid[level,y-1,x]

    return tally

    

In [243]:
# each map is a recursive grid. what's the number of bugs after 200 mins. 
#Initially, no other levels contain bugs.
# expand the grid to (501 dims,7,7) 


# need a function that fetches the neighbors: 

levelzero = 250
mins = 200

grid = np.zeros((500,7,7)).astype(int)

for y,char in enumerate(dat):
    for x,c in enumerate(char[0:-1]):
        #print(c)
        if c == '#':
            grid[levelzero,y+1,x+1] = 1
        elif c == '.':
            grid[levelzero,y+1,x+1] = 0
            
for generation in range(0,mins):
    #nextgrid = np.zeros((500,7,7)).astype(int)
    for level in range(249-generation,251+generation):
        #print(level)
        for x in range(1,6):
            for y in range(1,6):
                bugtally = 0
                bugtally = get_adjacent_tally(grid,level,x,y)

                #bugs die if next to another bug

                if grid[level,y,x] == 0 and (bugtally == 1):
                    grid[level,y,x]=1

                if grid[level,y,x] == 0 and (bugtally == 2):
                    grid[y,x]=1
                if grid[level,y,x] == 1 and bugtally == 1:
                    grid[level,y,x]=1
                    
    grid[level,3,3] = 0


np.sum(grid)

2760