In [65]:
f = open('input-22.txt','r')
cmds = f.readlines()
f.close()

In [66]:
stack = []
for i in range(0,10007+1):
    stack.append(i)

In [10]:
stack[-1]

10007

In [32]:
import numpy as np

stack = np.arange(0,9)

In [40]:
n_cut(stack,-4)

array([6, 7, 8, 0, 1, 2, 3, 4, 5])

In [322]:
def new_stack(stackl):
    return np.flip(stackl)


def n_cut(stackl,n):
    if n<0:
        return np.roll(stackl,-n)
    return np.roll(stackl,-n)


def deal_increment(stackl,n):
    tmp_stack = []
    newdeck = np.ones(len(stackl))*-1
    p = 0
    npos=0
    for card in stackl:
        newdeck[npos] = card
        npos+=n
        npos = npos%(len(stackl))
    #print(newdeck)
    assert (newdeck==-1).sum() == 0
    return newdeck
        


In [323]:
12%9

3

In [324]:
n_cut(np.arange(0,10),-4)

array([6, 7, 8, 9, 0, 1, 2, 3, 4, 5])

In [325]:
stack = np.arange(0,10)

#print(len(stack))
ans = deal_increment(stack,3)


print(len(stack),len(ans))
ans

10 10


array([0., 7., 4., 1., 8., 5., 2., 9., 6., 3.])

In [326]:
#0 7 4 1 8 5 2 9 6 3 

In [327]:
stack = np.arange(0,10007)
for cmd in cmds:
    if 'deal into new stack' in cmd:
        #print('New stack')
        stack = new_stack(stack)
    elif 'cut' in cmd:
        amt = int(cmd.split(' ')[-1])
        print('cut',amt)
        stack = n_cut(stack,amt)
    elif 'deal with increment' in cmd:
        amt = int(cmd.split(' ')[-1])
        print('Dealing',amt)
        stack = deal_increment(stack,amt)
    else:
        print('something else')

Dealing 10
cut -5908
Dealing 75
cut 8705
Dealing 49
cut -1609
Dealing 69
cut 7797
cut -6211
Dealing 10
cut 6188
Dealing 57
cut -1659
Dealing 16
cut -5930
cut -2758
Dealing 33
cut -3275
Dealing 39
cut -1301
Dealing 50
cut 7837
Dealing 74
cut 1200
Dealing 23
cut -9922
Dealing 65
cut 4896
Dealing 61
cut 5945
Dealing 9
Dealing 2
cut -8205
Dealing 75
cut -4063
Dealing 40
cut -7366
Dealing 51
cut 7213
cut 4763
Dealing 43
cut 3963
Dealing 50
cut -8856
Dealing 43
cut 8604
Dealing 72
cut -7026
Dealing 25
cut 7843
Dealing 71
cut -1272
Dealing 64
cut 7770
Dealing 18
cut -5278
Dealing 67
Dealing 18
cut 2216
Dealing 42
cut 3206
Dealing 14
cut -6559
Dealing 12
Dealing 75
Dealing 41
cut 7378
Dealing 44
cut 774
Dealing 60
cut 7357
Dealing 41
cut 479
Dealing 40
cut 5146
Dealing 13
cut 2017
Dealing 35
cut 9218
Dealing 22
cut -2462
Dealing 23
cut -1820
Dealing 69


In [332]:
np.where(stack == 2019)[0][0]

4649

In [370]:
card_len = 119315717514047
times = 101741582076661
final_card = 2020
#card_len, final_card, times = 10007, 4649, 1

a = 1
b = 0

#need to go backwards
for cmd in reversed(cmds):
    if cmd.startswith('deal into new stack'):
        #print('New stack')
        #stack = new_stack(stack)
        
        b += 1
        a *= -1
        b *= -1
        
    elif 'cut' in cmd:
        amt = int(cmd.split(' ')[-1])
        #print('cut',amt)
        #stack = n_cut(stack,amt)
        
        b += amt
        
    elif cmd.startswith('deal with increment'):
        amt = int(cmd.split(' ')[-1])
        #print('Dealing',amt)
        #stack = deal_increment(stack,amt)
        
        p = pow(amt, card_len-2,card_len)
        a *= p
        b *= p

    else:
        print('something else')
        break
        
    a %= card_len
    b %= card_len

    

print((
    pow(a, times, card_len) * final_card +
    b * (pow(a, times, card_len) +card_len- 1)
      * (pow(a-1, card_len - 2, card_len))
) % card_len)



68849657493596
